version: '3.4'

services:
  gerenciamentofrota.api:
    container_name: gerenciamentofrota.api
    image: ${DOCKER_REGISTRY-}gerenciamentofrotaapi
    build:
      context: .
      dockerfile: GerenciamentoFrota.API/Dockerfile
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
      - 27017:27017

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes: 
      - cache:/data
    environment:
      REDIS_PASSWORD: pwd
    ports:
      - 6379:6379

  redis-commander:
     container_name: redis-commander
     restart: always
     image: rediscommander/redis-commander:latest
     environment:
       REDIS_HOSTS: local:redis:6379
     ports:
       - 8081:8081

volumes:
  cache:
    driver: local
    
